version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    networks:
      - app-network
      
  frontend:
    build: ./frontend
    networks:
      - app-network

  nginx:
    image: nginx:latest
    ports:
      - "8000:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
  